### ISSUE TITLE
setup issue on IOS

### ISSUE THREAD

**Issue by 1l6r5d** [QuentinFung/appledaily-unblock#1]
after install the shortcut and the script
and cannot run with safari
can you check or any guide for it?
Thank you, Quentin

**Comment by QuentinFung** [comment]
hi, are you running the shortcut using the following steps?

1. go to Apple Daily with Safari
2. press "Share"
3. choose "Shortcuts"
4. choose "蘋果日報免登記會員🍎"
5. the script will be run and the Apple Daily page will be refreshed with content loaded

pls let me know any error msg you encountered
