### ISSUE TITLE
Cant open in shortcut IOS13.3

### ISSUE THREAD

**Issue by seanscale** [QuentinFung/appledaily-unblock#3]
This shorcut cant open in IOS13.3
it shows 目前不支援將捷徑輸入為檔案，請使用ICLOUD分享捷徑(Shortcuts are not currently supported as files. Use ICLOUD to share shortcuts)
 please  help thx a lot

**Comment by QuentinFung** [comment]
[https://www.icloud.com/shortcuts/7caa719cff7c4056b4674f45b7727c6d](url)
試試看這個

**Comment by seanscale** [comment]
it works thx  a lot
