### ISSUE TITLE
Doesn’t work for Apple Daily iOS shortcut

### ISSUE THREAD

**Issue by fiesta2004hk** [QuentinFung/appledaily-unblock#4]
I updated yr latest version shortcut for ios v1.17. Recently I found it doesn’t work  on 13.3. I also tried on iOS 12.4, both iOS doesn’t work. Apple daily login pop-up always on top and never remove. Thank you so much if u can take a look.

**Comment by QuentinFung** [comment]
[https://www.icloud.com/shortcuts/7caa719cff7c4056b4674f45b7727c6d](https://www.icloud.com/shortcuts/7caa719cff7c4056b4674f45b7727c6d)
試試看這個

**Comment by fiesta2004hk** [comment]
Thank you so much your effort.

**Comment by fiesta2004hk** [comment]
> https://www.icloud.com/shortcuts/7caa719cff7c4056b4674f45b7727c6d
> 試試看這個

Thank you so much your effort.
