### ISSUE TITLE
需要特殊功能

### ISSUE THREAD

**Issue by 2020e** [QuentinFung/appledaily-unblock#5]
你好:
 https://tw.news.appledaily.com/international/20200124/DGQQTCFDVPR2NAAIONHU2QRXA4/ 

你可以將它的留言評論版進行調試嗎?添加"無限自動擴展"功能. 謝謝!

**Comment by QuentinFung** [comment]
hi, 那個是fb plugin 的留言功能, 已不是蘋果日報的網站範圍
你可以找找看有沒有其他extension 可做到這功能, 謝謝
