### ISSUE TITLE
果燃台無法使用

### ISSUE THREAD

**Issue by qizhenyu** [QuentinFung/appledaily-unblock#7]
您好，因為果燃台近期更換了網址，由原先的 hk.feature.appledaily.com 更換成了 hk.applefruity.com

導致插件在果燃台上無法使用，希望可以更新一下插件，謝謝！

**Comment by QuentinFung** [comment]
v1.19 修正了這個問題，待Google 審批過後更新就可以了
謝謝你的回報

**Comment by qizhenyu** [comment]
可以使用了！感謝修正！
